---
rc_local_service_name: rc-local
rc_local_commands:
  - |
    dbus-uuidgen --ensure
    make -C /usr/local/pf conf/ssl/server.pem
    make -C /usr/local/pf conf/local_secret
    make -C /usr/local/pf/raddb/certs

    echo "" > /etc/issue
    echo "Welcome to the PacketFence-ZEN." >> /etc/issue
    echo "" >> /etc/issue
    echo "In order to configure your PacketFence installation, please connect to one of the following URLs:" >> /etc/issue
    
    while ! /usr/local/pf/bin/pfcmd pfconfig get resource::fqdn 2>&1| grep last_touch_cache > /dev/null ; do
            echo "Waiting for pfconfig to be online..."
    done
    echo "pfconfig is now online!"
    
    mgmt_ipaddr=`/usr/local/pf/bin/pfcmd pfconfig show interfaces::management_network`
    if [ "$mgmt_ipaddr" != "\$VAR1 = '';" ]; then
        mgmt_ipaddr=`echo $mgmt_ipaddr | grep Tip | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'`
        echo https://$mgmt_ipaddr:1443 >> /etc/issue
    else
        for IPADDR in `/sbin/ifconfig | grep -v 100.64.0.1 | sed '/broadcast/!d' | awk '{print $2}'`; do
                echo "https://$IPADDR:1443" >> /etc/issue
        done
    fi
    echo "" >> /etc/issue
    echo "" >> /etc/issue
    touch /var/lock/subsys/local
    
    exit 0
  - |
    
