---

hostapd__configs:
  - name: open
    hostapd__acct_server_addr: '{{ packetfence_server_mgmt_ip }}'
    hostapd__acct_server_port: 1813
    hostapd__acct_server_shared_secret: 'testing123'
    hostapd__auth_algs: 3
    hostapd__auth_server_addr: '{{ packetfence_server_mgmt_ip }}'
    hostapd__auth_server_port: 1812
    hostapd__auth_server_shared_secret: 'testing123'
    hostapd__ctrl_interface: '/var/run/hostapd'
    hostapd__ctrl_interface_group: 0
    hostapd__driver: 'nl80211'
    hostapd__hw_mode: 'g'
    hostapd__interface: 'wlan0'
    hostapd__logger_syslog: 1
    hostapd__macaddr_acl: 2
    hostapd__nas_identifier: '{{ ansible_fqdn }}'
    hostapd__own_ip_addr: '{{ hostvars[inventory_hostname]["mgmt_ip"] }}'
    hostapd__ssid: 'PF-Open'
    hostapd__vlan_file: '/etc/hostapd/hostapd_open.vlan'
    hostapd__dynamic_vlan: 1
    hostapd__radius_das_port: 3799
    hostapd__radius_das_client: '{{ packetfence_server_mgmt_ip }} testing123'
    hostapd__radius_das_require_event_timestamp: 0
    hostapd__radius_das_require_message_authenticator: 0

  - name: secure
    hostapd__acct_server_addr: '{{ packetfence_server_mgmt_ip }}'
    hostapd__acct_server_port: 1813
    hostapd__acct_server_shared_secret: 'testing123'
    hostapd__auth_algs: 3
    hostapd__auth_server_addr: '{{ packetfence_server_mgmt_ip }}'
    hostapd__auth_server_port: 1812
    hostapd__auth_server_shared_secret: 'testing123'
    hostapd__ctrl_interface: '/var/run/hostapd'
    hostapd__ctrl_interface_group: 0
    hostapd__driver: 'nl80211'
    hostapd__ieee8021x: 1
    hostapd__hw_mode: 'g'
    hostapd__interface: 'wlan0'
    hostapd__logger_syslog: 1
    hostapd__macaddr_acl: 2
    hostapd__nas_identifier: '{{ ansible_fqdn }}'
    hostapd__own_ip_addr: '{{ hostvars[inventory_hostname]["mgmt_ip"] }}'
    hostapd__ssid: 'PF-Secure'
    hostapd__wpa: 2
    hostapd__wpa_key_mgmt: 'WPA-EAP'
    hostapd__wpa_pairwise: 'CCMP'
    hostapd__vlan_file: '/etc/hostapd/hostapd_secure.vlan'
    hostapd__dynamic_vlan: 1
    hostapd__radius_das_port: 3799
    hostapd__radius_das_client: '{{ packetfence_server_mgmt_ip }} testing123'
    hostapd__radius_das_require_event_timestamp: 0
    hostapd__radius_das_require_message_authenticator: 0
